 version: '3.1'

 services:
    db:
      image: mysql:15.1
      container_name: govt_policy_db
      restart: always
      volumes:
        - ./sql:/docker-entrypoint-initdb.d/
      environment:
        MYSQL_DATABASE: "${DB}"
        MYSQL_USER: "${DBU}"
        MYSQL_PASSWORD: "${DBP}"
        MYSQL_RANDOM_ROOT_PASSWORD: "1"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: root
      restart: always
      environment:
        PMA_HOST: "${DB}"
        PMA_USER: "${DBU}"
        PMA_PASSWORD: "${DBP}"
        PMA_ARBITRARY: "1"
      ports:
        - 3306:80
    drupal:
      image: drupal:10-php8.2.4
      container_name: govt_policy
      restart: always
      port:
        - 3306:80
      working_dir: /opt
      volumes:
        - .:/opt:z
      environment:
        HOST: "${DB}"
        USER: "${DBU}"
        PASS: "${DBP}"